Cleaning of the tourism_hospitality_data and transformation into two csv: 
    - One filtered to only Paris
    - One for all the cities but with all the countries

In [9]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

file_path = Path(r"C:\Users\johan\Desktop\hotel_pricing_project\data\raw\Tourism_Hospitality_Industry_Analysis.csv")

df = pd.read_csv(file_path)

print("Archivo cargado correctamente")
print("Shape:", df.shape)
display(df.head())
print("\nColumnas:")
print(df.columns.tolist())

Archivo cargado correctamente
Shape: (500, 23)

,Country,City,Year,Month,Number_of_Tourists,Purpose_of_Visit,Average_Length_of_Stay,Tourist_Spending_USD,Hotel_Occupancy_Rate,Number_of_Hotels,...,Employment_in_Tourism,Contribution_to_GDP_Percent,Number_of_Flights,Airport_Passenger_Traffic,Transport_Infrastructure_Quality,Eco_Tourism_Revenue_USD,Carbon_Footprint_kg,Waste_Management_Rating,Tourist_Satisfaction_Score,Number_of_Online_Reviews
0,Italy,Venice,2022,2,171958,Cultural,12.4,1325.46,79.0,70,...,21850,2.9,3944,225203,2.3,48484.36,21075968.92,7.5,9.7,2533
1,India,Mumbai,2020,3,55311,Religious,14.9,3278.67,70.6,302,...,46434,12.6,2547,704811,9.8,19620.39,7535713.00,6.6,6.9,1367
2,Japan,Tokyo,2022,4,81551,Leisure,8.1,4369.73,74.0,378,...,15627,18.9,2561,255041,4.5,19240.21,15686948.95,3.2,8.4,875
3,United Kingdom,Manchester,2021,1,160510,Educational,4.3,2259.77,49.1,437,...,16653,5.0,4343,221829,1.3,94513.26,44927014.38,4.6,9.6,7729
4,Egypt,Luxor,2022,12,141387,Cultural,2.6,1963.99,59.4,387,...,26271,7.8,879,566588,2.3,69573.18,18354896.74,9.9,8.9,2127

Columnas:
['Country', 'City', 'Year', 'Month', 'Number_of_Tourists', 'Purpose_of_Visit', 'Average_Length_of_Stay', 'Tourist_Spending_USD', 'Hotel_Occupancy_Rate', 'Number_of_Hotels', 'Hotel_Rating', 'Average_Room_Price_USD', 'Tourism_Revenue_USD', 'Employment_in_Tourism', 'Contribution_to_GDP_Percent', 'Number_of_Flights', 'Airport_Passenger_Traffic', 'Transport_Infrastructure_Quality', 'Eco_Tourism_Revenue_USD', 'Carbon_Footprint_kg', 'Waste_Management_Rating', 'Tourist_Satisfaction_Score', 'Number_of_Online_Reviews']

In [10]:

df_clean = df.copy()


df_clean.columns = [col.strip().lower() for col in df_clean.columns]
df_clean.columns = [re.sub(r"[^a-z0-9]+", "_", col).strip("_") for col in df_clean.columns]


text_cols = df_clean.select_dtypes(include="object").columns

for col in text_cols:
    df_clean[col] = df_clean[col].astype(str).str.strip()


print("Shape:", df_clean.shape)

print("\nNulos por columna:")
print(df_clean.isna().sum())

print("\nDuplicados:", df_clean.duplicated().sum())

print("\nColumnas limpias:")
print(df_clean.columns.tolist())

display(df_clean.head())

Shape: (500, 23)

Nulos por columna:
country                             0
city                                0
year                                0
month                               0
number_of_tourists                  0
purpose_of_visit                    0
average_length_of_stay              0
tourist_spending_usd                0
hotel_occupancy_rate                0
number_of_hotels                    0
hotel_rating                        0
average_room_price_usd              0
tourism_revenue_usd                 0
employment_in_tourism               0
contribution_to_gdp_percent         0
number_of_flights                   0
airport_passenger_traffic           0
transport_infrastructure_quality    0
eco_tourism_revenue_usd             0
carbon_footprint_kg                 0
waste_management_rating             0
tourist_satisfaction_score          0
number_of_online_reviews            0
dtype: int64

Duplicados: 0

Columnas limpias:
['country', 'city', 'year', 'month', 'number_of_tourists', 'purpose_of_visit', 'average_length_of_stay', 'tourist_spending_usd', 'hotel_occupancy_rate', 'number_of_hotels', 'hotel_rating', 'average_room_price_usd', 'tourism_revenue_usd', 'employment_in_tourism', 'contribution_to_gdp_percent', 'number_of_flights', 'airport_passenger_traffic', 'transport_infrastructure_quality', 'eco_tourism_revenue_usd', 'carbon_footprint_kg', 'waste_management_rating', 'tourist_satisfaction_score', 'number_of_online_reviews']

,country,city,year,month,number_of_tourists,purpose_of_visit,average_length_of_stay,tourist_spending_usd,hotel_occupancy_rate,number_of_hotels,...,employment_in_tourism,contribution_to_gdp_percent,number_of_flights,airport_passenger_traffic,transport_infrastructure_quality,eco_tourism_revenue_usd,carbon_footprint_kg,waste_management_rating,tourist_satisfaction_score,number_of_online_reviews
0,Italy,Venice,2022,2,171958,Cultural,12.4,1325.46,79.0,70,...,21850,2.9,3944,225203,2.3,48484.36,21075968.92,7.5,9.7,2533
1,India,Mumbai,2020,3,55311,Religious,14.9,3278.67,70.6,302,...,46434,12.6,2547,704811,9.8,19620.39,7535713.00,6.6,6.9,1367
2,Japan,Tokyo,2022,4,81551,Leisure,8.1,4369.73,74.0,378,...,15627,18.9,2561,255041,4.5,19240.21,15686948.95,3.2,8.4,875
3,United Kingdom,Manchester,2021,1,160510,Educational,4.3,2259.77,49.1,437,...,16653,5.0,4343,221829,1.3,94513.26,44927014.38,4.6,9.6,7729
4,Egypt,Luxor,2022,12,141387,Cultural,2.6,1963.99,59.4,387,...,26271,7.8,879,566588,2.3,69573.18,18354896.74,9.9,8.9,2127

In [13]:
# 1. Crear nombre del mes
month_map = {
    1: "January", 2: "February", 3: "March", 4: "April",
    5: "May", 6: "June", 7: "July", 8: "August",
    9: "September", 10: "October", 11: "November", 12: "December"
}

df_clean["month_name"] = df_clean["month"].map(month_map)

# 2. Convertir hotel_rating a numérico sin warning
rating_map = {
    "1-star": 1,
    "2-star": 2,
    "3-star": 3,
    "4-star": 4,
    "5-star": 5,
    "unrated": np.nan,
    "Unrated": np.nan
}

df_clean["hotel_rating_num"] = df_clean["hotel_rating"].map(rating_map)

# 3. Filtrar solo París
df_paris = df_clean[
    (df_clean["city"].str.lower() == "paris") &
    (df_clean["country"].str.lower() == "france")
].copy()

# 4. Comprobaciones
print("Shape df_clean:", df_clean.shape)
print("Shape df_paris:", df_paris.shape)

print("\nValores únicos de hotel_rating:")
print(sorted(df_clean["hotel_rating"].unique()))

print("\nPrimeras filas de df_paris:")
display(df_paris.head())

Shape df_clean: (500, 25)
Shape df_paris: (4, 25)

Valores únicos de hotel_rating:
['1-star', '2-star', '3-star', '4-star', '5-star', 'Unrated']

Primeras filas de df_paris:

,country,city,year,month,number_of_tourists,purpose_of_visit,average_length_of_stay,tourist_spending_usd,hotel_occupancy_rate,number_of_hotels,...,number_of_flights,airport_passenger_traffic,transport_infrastructure_quality,eco_tourism_revenue_usd,carbon_footprint_kg,waste_management_rating,tourist_satisfaction_score,number_of_online_reviews,month_name,hotel_rating_num
9,France,Paris,2024,8,71959,Leisure,8.9,2681.73,74.6,283,...,4243,643128,4.6,12779.37,14504499.71,3.2,8.5,7654,August,1.0
125,France,Paris,2022,1,113936,Educational,7.8,715.24,41.9,136,...,3211,782176,9.6,19099.76,27492820.99,3.7,6.7,5430,January,1.0
229,France,Paris,2020,9,73185,Leisure,13.7,1415.63,43.3,71,...,2839,168094,1.6,21972.05,9487862.14,4.4,9.0,2482,September,5.0
359,France,Paris,2022,5,152127,Religious,4.0,2178.50,50.5,157,...,1508,201770,8.6,33638.45,73148482.08,4.1,9.9,4811,May,2.0

In [14]:
df_paris.columns

Index(['country', 'city', 'year', 'month', 'number_of_tourists',
       'purpose_of_visit', 'average_length_of_stay', 'tourist_spending_usd',
       'hotel_occupancy_rate', 'number_of_hotels', 'hotel_rating',
       'average_room_price_usd', 'tourism_revenue_usd',
       'employment_in_tourism', 'contribution_to_gdp_percent',
       'number_of_flights', 'airport_passenger_traffic',
       'transport_infrastructure_quality', 'eco_tourism_revenue_usd',
       'carbon_footprint_kg', 'waste_management_rating',
       'tourist_satisfaction_score', 'number_of_online_reviews', 'month_name',
       'hotel_rating_num'],
      dtype='object')

In [ ]:
from pathlib import Path

output_folder = Path("../data/processed")
output_folder.mkdir(parents=True, exist_ok=True)


df_clean.to_csv(output_folder / "tourism_hospitality_cleaned.csv", index=False)
df_paris.to_csv(output_folder / "paris_tourism_hospitality_cleaned.csv", index=False)

print("File saved in:")
print((output_folder / "tourism_hospitality_cleaned.csv").resolve())
print((output_folder / "paris_tourism_hospitality_cleaned.csv").resolve())

Archivos guardados correctamente en:
C:\Users\johan\Desktop\hotel_pricing_project\data\processed\tourism_hospitality_cleaned.csv
C:\Users\johan\Desktop\hotel_pricing_project\data\processed\paris_tourism_hospitality_cleaned.csv